set(CMAKE_SYSTEM_NAME iOS)

if(NOT DEFINED SIMULATOR_ARCH)
    set(SIMULATOR_ARCH "${CMAKE_HOST_SYSTEM_PROCESSOR}")
endif()

set(CMAKE_SYSTEM_PROCESSOR "${SIMULATOR_ARCH}")
set(CMAKE_OSX_ARCHITECTURES "${SIMULATOR_ARCH}" CACHE STRING "" FORCE)
set(CMAKE_OSX_SYSROOT iphonesimulator CACHE STRING "" FORCE)
set(CMAKE_OSX_DEPLOYMENT_TARGET 15.0 CACHE STRING "" FORCE)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

execute_process(
    COMMAND xcrun --sdk iphonesimulator --find clang
    OUTPUT_VARIABLE IOS_SIM_CLANG
    OUTPUT_STRIP_TRAILING_WHITESPACE
    COMMAND_ERROR_IS_FATAL ANY
)
execute_process(
    COMMAND xcrun --sdk iphonesimulator --find clang++
    OUTPUT_VARIABLE IOS_SIM_CLANGXX
    OUTPUT_STRIP_TRAILING_WHITESPACE
    COMMAND_ERROR_IS_FATAL ANY
)

set(CMAKE_C_COMPILER "${IOS_SIM_CLANG}" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${IOS_SIM_CLANGXX}" CACHE FILEPATH "" FORCE)
set(CMAKE_OBJC_COMPILER "${IOS_SIM_CLANG}" CACHE FILEPATH "" FORCE)
set(CMAKE_OBJCXX_COMPILER "${IOS_SIM_CLANGXX}" CACHE FILEPATH "" FORCE)
