set(CMAKE_SYSTEM_NAME iOS)
set(CMAKE_SYSTEM_PROCESSOR arm64)
set(CMAKE_OSX_ARCHITECTURES arm64 CACHE STRING "" FORCE)
set(CMAKE_OSX_SYSROOT iphoneos CACHE STRING "" FORCE)
set(CMAKE_OSX_DEPLOYMENT_TARGET 15.0 CACHE STRING "" FORCE)

# CMake feature probes must not attempt to produce or run an iOS executable.
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

execute_process(
    COMMAND xcrun --sdk iphoneos --find clang
    OUTPUT_VARIABLE IOS_CLANG
    OUTPUT_STRIP_TRAILING_WHITESPACE
    COMMAND_ERROR_IS_FATAL ANY
)
execute_process(
    COMMAND xcrun --sdk iphoneos --find clang++
    OUTPUT_VARIABLE IOS_CLANGXX
    OUTPUT_STRIP_TRAILING_WHITESPACE
    COMMAND_ERROR_IS_FATAL ANY
)

set(CMAKE_C_COMPILER "${IOS_CLANG}" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${IOS_CLANGXX}" CACHE FILEPATH "" FORCE)
set(CMAKE_OBJC_COMPILER "${IOS_CLANG}" CACHE FILEPATH "" FORCE)
set(CMAKE_OBJCXX_COMPILER "${IOS_CLANGXX}" CACHE FILEPATH "" FORCE)

